version: 2

sources:
  - name: staging
    database: postgres-zoomcamp
    schema: public

    tables:
     
     - name: green_tripdata
     - name: yellow_tripdata

models:
  - name: stg_yellow_tripdata
    description: ""
    columns:
      - name: tripid
        data_type: text
        description: ""

      - name: vendorid
        data_type: integer
        description: ""

      - name: ratecodeid
        data_type: integer
        description: ""

      - name: pickup_locationid
        data_type: integer
        description: ""

      - name: dropoff_locationid
        data_type: integer
        description: ""

      - name: pickup_datetime
        data_type: timestamp without time zone
        description: ""

      - name: dropoff_datetime
        data_type: timestamp without time zone
        description: ""

      - name: store_and_fwd_flag
        data_type: text
        description: ""

      - name: passenger_count
        data_type: integer
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: integer
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: integer
        description: ""

      - name: payment_type_description
        data_type: text
        description: ""


  - name: stg_green_tripdata
    description: ""
    columns:
      - name: tripid
        data_type: text
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: vendorid
        data_type: integer
        description: ""

      - name: ratecodeid
        data_type: integer
        description: ""

      - name: pickup_locationid
        data_type: integer
        description: ""
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn

      - name: dropoff_locationid
        data_type: integer
        description: ""
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn

      - name: pickup_datetime
        data_type: timestamp without time zone
        description: ""

      - name: dropoff_datetime
        data_type: timestamp without time zone
        description: ""

      - name: store_and_fwd_flag
        data_type: text
        description: ""

      - name: passenger_count
        data_type: integer
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: integer
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: integer
        description: ""
        tests:
          - accepted_values:
              values: "{{ var ('payment_type_values') }}"
              severity: warn

      - name: payment_type_description
        data_type: text
        description: ""